name: Victoria Metrics Agent add-on
version: "1.132.1"
slug: victoria_metrics_agent
description: Victoria Metrics Agent add-on for long term storage as replacement for Prometheus and InfluxDB
url: https://github.com/lapo-luchini/homeassistant-addon-vmagent
webui: "http://[HOST]:[PORT:8429]/"
ingress: true
ingress_port: 8429
ingress_entry: /targets
watchdog: "http://[HOST]:[PORT:8429]/targets"
# host_network: true
ports:
  8429/tcp: null
ports_description:
  8429/tcp: Victoria Metrics Agent HTTP endpoint
arch:
  - aarch64
  - amd64
init: false
stage: stable
options:
  remoteWriteURL: ""
  additionalArguments: ""
  enableHTTPAuth: false
  username: ""
  password: ""
  enableNodeExporterScrape: false
  enablePrometheusScrape: false
  prometheusScrapeHTTPS: false
  prometheusScrapeInterval: "20s"
  prometheusScrapeTimeout: "15s"
  longelivedToken: ""
  homeassistantUrl: ""
schema:
  remoteWriteURL: "str?"
  additionalArguments: "str?"
  enableHTTPAuth: bool
  username: "str?"
  password: "password?"
  enableNodeExporterScrape: bool
  enablePrometheusScrape: bool
  prometheusScrapeHTTPS: bool
  prometheusScrapeInterval: "str?"
  prometheusScrapeTimeout: "str?"
  longelivedToken: "password?"
  homeassistantUrl: "str?"
